include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    use_build_context_synchronously: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.config.dart"
    - "**/*.freezed.dart"
  errors:
    unused_import: error