name: postsapp
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  http: ^1.0.0
  injectable: ^2.1.2
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
